from dataclasses import dataclass
from typing import Dict, List

from element_data import ELEMENTS


@dataclass(frozen=True)
class AllotropeData:
    name: str
    properties: Dict[str, str]


PROPERTY_LABELS = {
    "density": "标准状况密度 (kg/m³)",
    "melting_point": "熔点 (K)",
    "boiling_point": "沸点 (K)",
    "electronegativity": "电负性 (鲍林)",
    "vdw_radius": "范德华半径 (Å)",
    "speed_of_sound": "声速",
    "triple_point": "三相点",
    "critical_point": "临界点",
    "electrical_conductivity": "电导率",
    "thermal_conductivity": "热导率",
    "mohs_hardness": "莫氏硬度",
    "crystal_structure": "晶体结构",
}

PROPERTY_ORDER = list(PROPERTY_LABELS.keys())

WIKIPEDIA_ALLOTROPES: Dict[str, List[AllotropeData]] = {
    "H": [
        AllotropeData(
            name="氢气 (H₂)",
            properties={
                "density": "0.08988",
                "melting_point": "13.99",
                "boiling_point": "20.271",
                "electronegativity": "2.20",
                "vdw_radius": "1.20",
                "speed_of_sound": "1310 m/s",
                "triple_point": "13.8033 K, 7.042 kPa",
                "critical_point": "33.145 K, 1.296 MPa",
                "electrical_conductivity": "0 S/m",
                "thermal_conductivity": "0.1805 W/(m·K)",
            },
        ),
    ],
    "He": [
        AllotropeData(
            name="氦 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Li": [
        AllotropeData(
            name="锂 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Be": [
        AllotropeData(
            name="铍 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "B": [
        AllotropeData(
            name="硼 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "C": [
        AllotropeData(
            name="石墨",
            properties={
                "density": "2267",
                "melting_point": "3823",
                "boiling_point": "4300",
                "electronegativity": "2.55",
                "vdw_radius": "1.70",
                "speed_of_sound": "21000 m/s",
                "electrical_conductivity": "2.5 × 10⁵ S/m",
                "thermal_conductivity": "119–165 W/(m·K)",
                "mohs_hardness": "1–2",
                "crystal_structure": "六方晶系",
            },
        ),
        AllotropeData(
            name="金刚石",
            properties={
                "density": "3515",
                "melting_point": "3823",
                "boiling_point": "4300",
                "electronegativity": "2.55",
                "vdw_radius": "1.70",
                "speed_of_sound": "12000 m/s",
                "electrical_conductivity": "≈0 S/m",
                "thermal_conductivity": "2200 W/(m·K)",
                "mohs_hardness": "10",
                "crystal_structure": "立方晶系 (金刚石型)",
            },
        ),
    ],
    "N": [
        AllotropeData(
            name="氮 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "O": [
        AllotropeData(
            name="氧气 (O₂)",
            properties={
                "density": "1.429",
                "melting_point": "54.36",
                "boiling_point": "90.20",
                "electronegativity": "3.44",
                "vdw_radius": "1.52",
                "speed_of_sound": "317.5 m/s",
                "triple_point": "54.361 K, 0.1463 kPa",
                "critical_point": "154.59 K, 5.043 MPa",
                "electrical_conductivity": "0 S/m",
                "thermal_conductivity": "0.02658 W/(m·K)",
            },
        ),
    ],
    "F": [
        AllotropeData(
            name="氟 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ne": [
        AllotropeData(
            name="氖 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Na": [
        AllotropeData(
            name="钠 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Mg": [
        AllotropeData(
            name="镁 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Al": [
        AllotropeData(
            name="铝 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Si": [
        AllotropeData(
            name="硅 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "P": [
        AllotropeData(
            name="磷 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "S": [
        AllotropeData(
            name="硫 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cl": [
        AllotropeData(
            name="氯 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ar": [
        AllotropeData(
            name="氩 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "K": [
        AllotropeData(
            name="钾 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ca": [
        AllotropeData(
            name="钙 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Sc": [
        AllotropeData(
            name="钪 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ti": [
        AllotropeData(
            name="钛 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "V": [
        AllotropeData(
            name="钒 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cr": [
        AllotropeData(
            name="铬 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Mn": [
        AllotropeData(
            name="锰 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Fe": [
        AllotropeData(
            name="α-铁 (体心立方)",
            properties={
                "density": "7874",
                "melting_point": "1811",
                "boiling_point": "3134",
                "electronegativity": "1.83",
                "vdw_radius": "2.04",
                "speed_of_sound": "5120 m/s",
                "electrical_conductivity": "10.0 × 10⁶ S/m",
                "thermal_conductivity": "80.4 W/(m·K)",
                "mohs_hardness": "4.0",
                "crystal_structure": "体心立方",
            },
        ),
    ],
    "Co": [
        AllotropeData(
            name="钴 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ni": [
        AllotropeData(
            name="镍 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cu": [
        AllotropeData(
            name="铜 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Zn": [
        AllotropeData(
            name="锌 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ga": [
        AllotropeData(
            name="镓 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ge": [
        AllotropeData(
            name="锗 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "As": [
        AllotropeData(
            name="砷 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Se": [
        AllotropeData(
            name="硒 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Br": [
        AllotropeData(
            name="溴 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Kr": [
        AllotropeData(
            name="氪 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Rb": [
        AllotropeData(
            name="铷 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Sr": [
        AllotropeData(
            name="锶 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Y": [
        AllotropeData(
            name="钇 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Zr": [
        AllotropeData(
            name="锆 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Nb": [
        AllotropeData(
            name="铌 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Mo": [
        AllotropeData(
            name="钼 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Tc": [
        AllotropeData(
            name="锝 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ru": [
        AllotropeData(
            name="钌 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Rh": [
        AllotropeData(
            name="铑 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pd": [
        AllotropeData(
            name="钯 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ag": [
        AllotropeData(
            name="银 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cd": [
        AllotropeData(
            name="镉 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "In": [
        AllotropeData(
            name="铟 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Sn": [
        AllotropeData(
            name="锡 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Sb": [
        AllotropeData(
            name="锑 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Te": [
        AllotropeData(
            name="碲 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "I": [
        AllotropeData(
            name="碘 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Xe": [
        AllotropeData(
            name="氙 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cs": [
        AllotropeData(
            name="铯 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ba": [
        AllotropeData(
            name="钡 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "La": [
        AllotropeData(
            name="镧 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "La": [
        AllotropeData(
            name="镧 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ce": [
        AllotropeData(
            name="铈 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pr": [
        AllotropeData(
            name="镨 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Nd": [
        AllotropeData(
            name="钕 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pm": [
        AllotropeData(
            name="钷 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Sm": [
        AllotropeData(
            name="钐 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Eu": [
        AllotropeData(
            name="铕 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Gd": [
        AllotropeData(
            name="钆 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Tb": [
        AllotropeData(
            name="铽 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Dy": [
        AllotropeData(
            name="镝 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ho": [
        AllotropeData(
            name="钬 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Er": [
        AllotropeData(
            name="铒 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Tm": [
        AllotropeData(
            name="铥 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Yb": [
        AllotropeData(
            name="镱 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Lu": [
        AllotropeData(
            name="镥 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Hf": [
        AllotropeData(
            name="铪 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ta": [
        AllotropeData(
            name="钽 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "W": [
        AllotropeData(
            name="钨 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Re": [
        AllotropeData(
            name="铼 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Os": [
        AllotropeData(
            name="锇 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ir": [
        AllotropeData(
            name="铱 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pt": [
        AllotropeData(
            name="铂 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Au": [
        AllotropeData(
            name="金 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Hg": [
        AllotropeData(
            name="汞 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Tl": [
        AllotropeData(
            name="铊 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pb": [
        AllotropeData(
            name="铅 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Bi": [
        AllotropeData(
            name="铋 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Po": [
        AllotropeData(
            name="钋 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "At": [
        AllotropeData(
            name="砹 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Rn": [
        AllotropeData(
            name="氡 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Fr": [
        AllotropeData(
            name="钫 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ra": [
        AllotropeData(
            name="镭 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ac": [
        AllotropeData(
            name="锕 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ac": [
        AllotropeData(
            name="锕 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Th": [
        AllotropeData(
            name="钍 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pa": [
        AllotropeData(
            name="镤 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "U": [
        AllotropeData(
            name="铀 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Np": [
        AllotropeData(
            name="镎 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Pu": [
        AllotropeData(
            name="钚 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Am": [
        AllotropeData(
            name="镅 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cm": [
        AllotropeData(
            name="锔 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Bk": [
        AllotropeData(
            name="锫 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cf": [
        AllotropeData(
            name="锎 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Es": [
        AllotropeData(
            name="锿 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Fm": [
        AllotropeData(
            name="镄 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Md": [
        AllotropeData(
            name="钔 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "No": [
        AllotropeData(
            name="锘 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Lr": [
        AllotropeData(
            name="铹 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Rf": [
        AllotropeData(
            name="𬬻 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Db": [
        AllotropeData(
            name="𬭊 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Sg": [
        AllotropeData(
            name="𬭳 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Bh": [
        AllotropeData(
            name="𬭛 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Hs": [
        AllotropeData(
            name="𬭶 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Mt": [
        AllotropeData(
            name="鿏 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ds": [
        AllotropeData(
            name="𫟼 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Rg": [
        AllotropeData(
            name="𬬭 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Cn": [
        AllotropeData(
            name="鿔 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Nh": [
        AllotropeData(
            name="鿭 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Fl": [
        AllotropeData(
            name="𫓧 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Mc": [
        AllotropeData(
            name="镆 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Lv": [
        AllotropeData(
            name="𫟷 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Ts": [
        AllotropeData(
            name="鿬 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],
    "Og": [
        AllotropeData(
            name="鿫 单质",
            properties={
                "density": "未知",
                "melting_point": "未知",
                "boiling_point": "未知",
                "electronegativity": "未知",
                "vdw_radius": "未知",
                "speed_of_sound": "未知",
                "triple_point": "未知",
                "critical_point": "未知",
                "electrical_conductivity": "未知",
                "thermal_conductivity": "未知",
                "mohs_hardness": "未知",
                "crystal_structure": "未知",
            },
        ),
    ],}

DEFAULT_ALLOTROPES: Dict[str, List[AllotropeData]] = {
    element.symbol: [AllotropeData(name=f"{element.name_cn} 单质", properties={})]
    for element in ELEMENTS
}


def get_allotropes(symbol: str) -> List[AllotropeData]:
    return WIKIPEDIA_ALLOTROPES.get(symbol, DEFAULT_ALLOTROPES.get(symbol, []))
