from dataclasses import dataclass
from typing import Dict, List

from element_data import ELEMENTS


@dataclass(frozen=True)
class AllotropeData:
    name: str
    properties: Dict[str, str]


PROPERTY_LABELS = {
    "density": "标准状况密度 (kg/m³)",
    "melting_point": "熔点 (K)",
    "boiling_point": "沸点 (K)",
    "electronegativity": "电负性 (鲍林)",
    "vdw_radius": "范德华半径 (Å)",
    "speed_of_sound": "声速",
    "triple_point": "三相点",
    "critical_point": "临界点",
    "electrical_conductivity": "电导率",
    "thermal_conductivity": "热导率",
    "mohs_hardness": "莫氏硬度",
    "crystal_structure": "晶体结构",
}

PROPERTY_ORDER = list(PROPERTY_LABELS.keys())

WIKIPEDIA_ALLOTROPES: Dict[str, List[AllotropeData]] = {
    "H": [
        AllotropeData(
            name="氢气 (H₂)",
            properties={
                "density": "0.08988",
                "melting_point": "13.99",
                "boiling_point": "20.271",
                "electronegativity": "2.20",
                "vdw_radius": "1.20",
                "speed_of_sound": "1310 m/s",
                "triple_point": "13.8033 K, 7.042 kPa",
                "critical_point": "33.145 K, 1.296 MPa",
                "electrical_conductivity": "0 S/m",
                "thermal_conductivity": "0.1805 W/(m·K)",
            },
        ),
    ],
    "He": [
        AllotropeData(
            name="氦 单质",
            properties={
                "density": "0.1786",
                "melting_point": "0.95",
                "boiling_point": "4.222",
                "electronegativity": None,
                "vdw_radius": "1.4",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.152",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Li": [
        AllotropeData(
            name="锂 单质",
            properties={
                "density": "534",
                "melting_point": "453.65",
                "boiling_point": "1603",
                "electronegativity": "0.98",
                "vdw_radius": "1.82",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "84.8",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Be": [
        AllotropeData(
            name="铍 单质",
            properties={
                "density": "1850",
                "melting_point": "1560",
                "boiling_point": "2742",
                "electronegativity": "1.57",
                "vdw_radius": "1.53",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "201",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "B": [
        AllotropeData(
            name="硼 单质",
            properties={
                "density": "2080",
                "melting_point": "2349",
                "boiling_point": "4200",
                "electronegativity": "2.04",
                "vdw_radius": "1.92",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "27.4",
                "mohs_hardness": None,
                "crystal_structure": "TET",
            },
        ),
    ],
    "C": [
        AllotropeData(
            name="石墨",
            properties={
                "density": "2267",
                "melting_point": "3823",
                "boiling_point": "4300",
                "electronegativity": "2.55",
                "vdw_radius": "1.70",
                "speed_of_sound": "21000 m/s",
                "electrical_conductivity": "2.5 × 10⁵ S/m",
                "thermal_conductivity": "119–165 W/(m·K)",
                "mohs_hardness": "1–2",
                "crystal_structure": "六方晶系",
            },
        ),
        AllotropeData(
            name="金刚石",
            properties={
                "density": "3515",
                "melting_point": "3823",
                "boiling_point": "4300",
                "electronegativity": "2.55",
                "vdw_radius": "1.70",
                "speed_of_sound": "12000 m/s",
                "electrical_conductivity": "≈0 S/m",
                "thermal_conductivity": "2200 W/(m·K)",
                "mohs_hardness": "10",
                "crystal_structure": "立方晶系 (金刚石型)",
            },
        ),
    ],
    "N": [
        AllotropeData(
            name="氮 单质",
            properties={
                "density": "1.251",
                "melting_point": "63.15",
                "boiling_point": "77.355",
                "electronegativity": "3.04",
                "vdw_radius": "1.55",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.026",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "O": [
        AllotropeData(
            name="氧气 (O₂)",
            properties={
                "density": "1.429",
                "melting_point": "54.36",
                "boiling_point": "90.20",
                "electronegativity": "3.44",
                "vdw_radius": "1.52",
                "speed_of_sound": "317.5 m/s",
                "triple_point": "54.361 K, 0.1463 kPa",
                "critical_point": "154.59 K, 5.043 MPa",
                "electrical_conductivity": "0 S/m",
                "thermal_conductivity": "0.02658 W/(m·K)",
                "mohs_hardness": None,
                "crystal_structure": None,
            },
        ),
        AllotropeData(
            name="臭氧 (O₃)",
            properties={
                "density": "2.144",
                "melting_point": "81.0",
                "boiling_point": "161",
                "electronegativity": "3.44",
                "vdw_radius": "1.52",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": None,
            },
        ),
    ],
    "F": [
        AllotropeData(
            name="氟 单质",
            properties={
                "density": "1.696",
                "melting_point": "53.48",
                "boiling_point": "85.03",
                "electronegativity": "3.98",
                "vdw_radius": "1.47",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.028",
                "mohs_hardness": None,
                "crystal_structure": "MCL",
            },
        ),
    ],
    "Ne": [
        AllotropeData(
            name="氖 单质",
            properties={
                "density": "0.9002",
                "melting_point": "24.56",
                "boiling_point": "27.104",
                "electronegativity": "0",
                "vdw_radius": "1.54",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.0493",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Na": [
        AllotropeData(
            name="钠 单质",
            properties={
                "density": "968",
                "melting_point": "370.944",
                "boiling_point": "1156.09",
                "electronegativity": "0.93",
                "vdw_radius": "2.27",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "142",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Mg": [
        AllotropeData(
            name="镁 单质",
            properties={
                "density": "1738",
                "melting_point": "923",
                "boiling_point": "1363",
                "electronegativity": "1.31",
                "vdw_radius": "1.73",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "156",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Al": [
        AllotropeData(
            name="铝 单质",
            properties={
                "density": "2700",
                "melting_point": "933.47",
                "boiling_point": "2743",
                "electronegativity": "1.61",
                "vdw_radius": "1.84",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "237",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Si": [
        AllotropeData(
            name="硅 单质",
            properties={
                "density": "2329",
                "melting_point": "1687",
                "boiling_point": "3538",
                "electronegativity": "1.9",
                "vdw_radius": "2.1",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "149",
                "mohs_hardness": None,
                "crystal_structure": "DIA",
            },
        ),
    ],
    "P": [
        AllotropeData(
            name="白磷 (P₄)",
            properties={
                "density": "1820",
                "melting_point": "317.3",
                "boiling_point": "553.15",
                "electronegativity": "2.19",
                "vdw_radius": "1.8",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": None,
            },
        ),
        AllotropeData(
            name="红磷",
            properties={
                "density": "2340",
                "melting_point": "863.15",
                "boiling_point": None,
                "electronegativity": "2.19",
                "vdw_radius": "1.8",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": None,
            },
        ),
        AllotropeData(
            name="黑磷",
            properties={
                "density": "2690",
                "melting_point": "883",
                "boiling_point": None,
                "electronegativity": "2.19",
                "vdw_radius": "1.8",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": None,
            },
        ),
    ],
    "S": [
        AllotropeData(
            name="斜方硫 (α-S)",
            properties={
                "density": "2080",
                "melting_point": "368.4",
                "boiling_point": "717.8",
                "electronegativity": "2.58",
                "vdw_radius": "1.8",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "Orthorhombic",
            },
        ),
        AllotropeData(
            name="单斜硫 (β-S)",
            properties={
                "density": "1960",
                "melting_point": "388.36",
                "boiling_point": "717.8",
                "electronegativity": "2.58",
                "vdw_radius": "1.8",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "Monoclinic",
            },
        ),
    ],
    "Cl": [
        AllotropeData(
            name="氯 单质",
            properties={
                "density": "3.2",
                "melting_point": "171.6",
                "boiling_point": "239.11",
                "electronegativity": "3.16",
                "vdw_radius": "1.75",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.009",
                "mohs_hardness": None,
                "crystal_structure": "ORC",
            },
        ),
    ],
    "Ar": [
        AllotropeData(
            name="氩 单质",
            properties={
                "density": "1.784",
                "melting_point": "83.81",
                "boiling_point": "87.302",
                "electronegativity": "0",
                "vdw_radius": "1.88",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.0177",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "K": [
        AllotropeData(
            name="钾 单质",
            properties={
                "density": "862",
                "melting_point": "336.7",
                "boiling_point": "1032",
                "electronegativity": "0.82",
                "vdw_radius": "2.75",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "79",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Ca": [
        AllotropeData(
            name="钙 单质",
            properties={
                "density": "1550",
                "melting_point": "1115",
                "boiling_point": "1757",
                "electronegativity": "1",
                "vdw_radius": "2.31",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "201",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Sc": [
        AllotropeData(
            name="钪 单质",
            properties={
                "density": "2985",
                "melting_point": "1814",
                "boiling_point": "3109",
                "electronegativity": "1.36",
                "vdw_radius": "2.11",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "15.8",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ti": [
        AllotropeData(
            name="钛 单质",
            properties={
                "density": "4506",
                "melting_point": "1941",
                "boiling_point": "3560",
                "electronegativity": "1.54",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "21.9",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "V": [
        AllotropeData(
            name="钒 单质",
            properties={
                "density": "6000",
                "melting_point": "2183",
                "boiling_point": "3680",
                "electronegativity": "1.63",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "30.7",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Cr": [
        AllotropeData(
            name="铬 单质",
            properties={
                "density": "7190",
                "melting_point": "2180",
                "boiling_point": "2944",
                "electronegativity": "1.66",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "93.9",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Mn": [
        AllotropeData(
            name="锰 单质",
            properties={
                "density": "7210",
                "melting_point": "1519",
                "boiling_point": "2334",
                "electronegativity": "1.55",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "7.8",
                "mohs_hardness": None,
                "crystal_structure": "CUB",
            },
        ),
    ],
    "Fe": [
        AllotropeData(
            name="α-铁 (体心立方)",
            properties={
                "density": "7874",
                "melting_point": "1811",
                "boiling_point": "3134",
                "electronegativity": "1.83",
                "vdw_radius": "2.04",
                "speed_of_sound": "5120 m/s",
                "electrical_conductivity": "10.0 × 10⁶ S/m",
                "thermal_conductivity": "80.4 W/(m·K)",
                "mohs_hardness": "4.0",
                "crystal_structure": "体心立方",
            },
        ),
    ],
    "Co": [
        AllotropeData(
            name="钴 单质",
            properties={
                "density": "8900",
                "melting_point": "1768",
                "boiling_point": "3200",
                "electronegativity": "1.88",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "100",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ni": [
        AllotropeData(
            name="镍 单质",
            properties={
                "density": "8908",
                "melting_point": "1728",
                "boiling_point": "3003",
                "electronegativity": "1.91",
                "vdw_radius": "1.63",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "90.9",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Cu": [
        AllotropeData(
            name="铜 单质",
            properties={
                "density": "8960",
                "melting_point": "1357.77",
                "boiling_point": "2835",
                "electronegativity": "1.9",
                "vdw_radius": "1.4",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "401",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Zn": [
        AllotropeData(
            name="锌 单质",
            properties={
                "density": "7140",
                "melting_point": "692.68",
                "boiling_point": "1180",
                "electronegativity": "1.65",
                "vdw_radius": "1.39",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "116",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ga": [
        AllotropeData(
            name="镓 单质",
            properties={
                "density": "5910",
                "melting_point": "302.9146",
                "boiling_point": "2673",
                "electronegativity": "1.81",
                "vdw_radius": "1.87",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "28.1",
                "mohs_hardness": None,
                "crystal_structure": "ORC",
            },
        ),
    ],
    "Ge": [
        AllotropeData(
            name="锗 单质",
            properties={
                "density": "5323",
                "melting_point": "1211.4",
                "boiling_point": "3106",
                "electronegativity": "2.01",
                "vdw_radius": "2.11",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "60.2",
                "mohs_hardness": None,
                "crystal_structure": "DIA",
            },
        ),
    ],
    "As": [
        AllotropeData(
            name="砷 单质",
            properties={
                "density": "5727",
                "melting_point": "1090",
                "boiling_point": "876",
                "electronegativity": "2.18",
                "vdw_radius": "1.85",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "50.2",
                "mohs_hardness": None,
                "crystal_structure": "RHL",
            },
        ),
    ],
    "Se": [
        AllotropeData(
            name="灰硒 (hexagonal)",
            properties={
                "density": "4810",
                "melting_point": "494",
                "boiling_point": "958",
                "electronegativity": "2.55",
                "vdw_radius": "1.9",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "Hexagonal",
            },
        ),
        AllotropeData(
            name="玻璃态硒 (vitreous)",
            properties={
                "density": "4280",
                "melting_point": "453",
                "boiling_point": "958",
                "electronegativity": "2.55",
                "vdw_radius": "1.9",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": None,
            },
        ),
    ],
    "Br": [
        AllotropeData(
            name="溴 单质",
            properties={
                "density": "3102.8",
                "melting_point": "265.8",
                "boiling_point": "332",
                "electronegativity": "2.96",
                "vdw_radius": "1.85",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.005",
                "mohs_hardness": None,
                "crystal_structure": "ORC",
            },
        ),
    ],
    "Kr": [
        AllotropeData(
            name="氪 单质",
            properties={
                "density": "3.749",
                "melting_point": "115.78",
                "boiling_point": "119.93",
                "electronegativity": "3",
                "vdw_radius": "2.02",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.0095",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Rb": [
        AllotropeData(
            name="铷 单质",
            properties={
                "density": "1532",
                "melting_point": "312.45",
                "boiling_point": "961",
                "electronegativity": "0.82",
                "vdw_radius": "3.03",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "58.2",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Sr": [
        AllotropeData(
            name="锶 单质",
            properties={
                "density": "2640",
                "melting_point": "1050",
                "boiling_point": "1650",
                "electronegativity": "0.95",
                "vdw_radius": "2.49",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "35.4",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Y": [
        AllotropeData(
            name="钇 单质",
            properties={
                "density": "4472",
                "melting_point": "1799",
                "boiling_point": "3203",
                "electronegativity": "1.22",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "17.2",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Zr": [
        AllotropeData(
            name="锆 单质",
            properties={
                "density": "6520",
                "melting_point": "2128",
                "boiling_point": "4650",
                "electronegativity": "1.33",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "22.7",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Nb": [
        AllotropeData(
            name="铌 单质",
            properties={
                "density": "8570",
                "melting_point": "2750",
                "boiling_point": "5017",
                "electronegativity": "1.6",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "53.7",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Mo": [
        AllotropeData(
            name="钼 单质",
            properties={
                "density": "10280",
                "melting_point": "2896",
                "boiling_point": "4912",
                "electronegativity": "2.16",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "138",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Tc": [
        AllotropeData(
            name="锝 单质",
            properties={
                "density": "11000",
                "melting_point": "2430",
                "boiling_point": "4538",
                "electronegativity": "1.9",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "50.6",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ru": [
        AllotropeData(
            name="钌 单质",
            properties={
                "density": "12450",
                "melting_point": "2607",
                "boiling_point": "4423",
                "electronegativity": "2.2",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "117",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Rh": [
        AllotropeData(
            name="铑 单质",
            properties={
                "density": "12410",
                "melting_point": "2237",
                "boiling_point": "3968",
                "electronegativity": "2.28",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "150",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Pd": [
        AllotropeData(
            name="钯 单质",
            properties={
                "density": "12023",
                "melting_point": "1828.05",
                "boiling_point": "3236",
                "electronegativity": "2.2",
                "vdw_radius": "1.63",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "71.8",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Ag": [
        AllotropeData(
            name="银 单质",
            properties={
                "density": "10490",
                "melting_point": "1234.93",
                "boiling_point": "2435",
                "electronegativity": "1.93",
                "vdw_radius": "1.72",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "429",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Cd": [
        AllotropeData(
            name="镉 单质",
            properties={
                "density": "8650",
                "melting_point": "594.22",
                "boiling_point": "1040",
                "electronegativity": "1.69",
                "vdw_radius": "1.58",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "96.9",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "In": [
        AllotropeData(
            name="铟 单质",
            properties={
                "density": "7310",
                "melting_point": "429.7485",
                "boiling_point": "2345",
                "electronegativity": "1.78",
                "vdw_radius": "1.93",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "81.8",
                "mohs_hardness": None,
                "crystal_structure": "TET",
            },
        ),
    ],
    "Sn": [
        AllotropeData(
            name="白锡 (β-Sn)",
            properties={
                "density": "7310",
                "melting_point": "505.08",
                "boiling_point": "2875",
                "electronegativity": "1.96",
                "vdw_radius": "2.17",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "Body-centered tetragonal",
            },
        ),
        AllotropeData(
            name="灰锡 (α-Sn)",
            properties={
                "density": "5750",
                "melting_point": "505.08",
                "boiling_point": "2875",
                "electronegativity": "1.96",
                "vdw_radius": "2.17",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "Diamond cubic",
            },
        ),
    ],
    "Sb": [
        AllotropeData(
            name="锑 单质",
            properties={
                "density": "6697",
                "melting_point": "903.78",
                "boiling_point": "1908",
                "electronegativity": "2.05",
                "vdw_radius": "2.06",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "24.43",
                "mohs_hardness": None,
                "crystal_structure": "RHL",
            },
        ),
    ],
    "Te": [
        AllotropeData(
            name="碲 单质",
            properties={
                "density": "6240",
                "melting_point": "722.66",
                "boiling_point": "1261",
                "electronegativity": "2.1",
                "vdw_radius": "2.06",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "14.3",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "I": [
        AllotropeData(
            name="碘 单质",
            properties={
                "density": "4933",
                "melting_point": "386.85",
                "boiling_point": "457.4",
                "electronegativity": "2.66",
                "vdw_radius": "1.98",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.45",
                "mohs_hardness": None,
                "crystal_structure": "ORC",
            },
        ),
    ],
    "Xe": [
        AllotropeData(
            name="氙 单质",
            properties={
                "density": "5.894",
                "melting_point": "161.4",
                "boiling_point": "165.051",
                "electronegativity": "2.6",
                "vdw_radius": "2.16",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.0057",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Cs": [
        AllotropeData(
            name="铯 单质",
            properties={
                "density": "1930",
                "melting_point": "301.7",
                "boiling_point": "944",
                "electronegativity": "0.79",
                "vdw_radius": "3.43",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "35.9",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Ba": [
        AllotropeData(
            name="钡 单质",
            properties={
                "density": "3510",
                "melting_point": "1000",
                "boiling_point": "2118",
                "electronegativity": "0.89",
                "vdw_radius": "2.68",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "18.4",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "La": [
        AllotropeData(
            name="镧 单质",
            properties={
                "density": "6162",
                "melting_point": "1193",
                "boiling_point": "3737",
                "electronegativity": "1.1",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "13.4",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "La": [
        AllotropeData(
            name="镧 单质",
            properties={
                "density": "6162",
                "melting_point": "1193",
                "boiling_point": "3737",
                "electronegativity": "1.1",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "13.4",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ce": [
        AllotropeData(
            name="铈 单质",
            properties={
                "density": "6770",
                "melting_point": "1068",
                "boiling_point": "3716",
                "electronegativity": "1.12",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "11.3",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Pr": [
        AllotropeData(
            name="镨 单质",
            properties={
                "density": "6770",
                "melting_point": "1208",
                "boiling_point": "3403",
                "electronegativity": "1.13",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "12.5",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Nd": [
        AllotropeData(
            name="钕 单质",
            properties={
                "density": "7010",
                "melting_point": "1297",
                "boiling_point": "3347",
                "electronegativity": "1.14",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "16.5",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Pm": [
        AllotropeData(
            name="钷 单质",
            properties={
                "density": "7260",
                "melting_point": "1315",
                "boiling_point": "3273",
                "electronegativity": "1.13",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "17.9",
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Sm": [
        AllotropeData(
            name="钐 单质",
            properties={
                "density": "7520",
                "melting_point": "1345",
                "boiling_point": "2173",
                "electronegativity": "1.17",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "13.3",
                "mohs_hardness": None,
                "crystal_structure": "RHL",
            },
        ),
    ],
    "Eu": [
        AllotropeData(
            name="铕 单质",
            properties={
                "density": "5264",
                "melting_point": "1099",
                "boiling_point": "1802",
                "electronegativity": "1.2",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "13.9",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Gd": [
        AllotropeData(
            name="钆 单质",
            properties={
                "density": "7900",
                "melting_point": "1585",
                "boiling_point": "3273",
                "electronegativity": "1.2",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "10.5",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Tb": [
        AllotropeData(
            name="铽 单质",
            properties={
                "density": "8230",
                "melting_point": "1629",
                "boiling_point": "3396",
                "electronegativity": "1.1",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "11.1",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Dy": [
        AllotropeData(
            name="镝 单质",
            properties={
                "density": "8540",
                "melting_point": "1680",
                "boiling_point": "2840",
                "electronegativity": "1.22",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "10.7",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ho": [
        AllotropeData(
            name="钬 单质",
            properties={
                "density": "8790",
                "melting_point": "1734",
                "boiling_point": "2873",
                "electronegativity": "1.23",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "16.2",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Er": [
        AllotropeData(
            name="铒 单质",
            properties={
                "density": "9066",
                "melting_point": "1802",
                "boiling_point": "3141",
                "electronegativity": "1.24",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "14.5",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Tm": [
        AllotropeData(
            name="铥 单质",
            properties={
                "density": "9320",
                "melting_point": "1818",
                "boiling_point": "2223",
                "electronegativity": "1.25",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "16.9",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Yb": [
        AllotropeData(
            name="镱 单质",
            properties={
                "density": "6900",
                "melting_point": "1097",
                "boiling_point": "1469",
                "electronegativity": "1.1",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "34.9",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Lu": [
        AllotropeData(
            name="镥 单质",
            properties={
                "density": "9841",
                "melting_point": "1925",
                "boiling_point": "3675",
                "electronegativity": "1.27",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "16.4",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Hf": [
        AllotropeData(
            name="铪 单质",
            properties={
                "density": "13310",
                "melting_point": "2506",
                "boiling_point": "4876",
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "23",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ta": [
        AllotropeData(
            name="钽 单质",
            properties={
                "density": "16690",
                "melting_point": "3290",
                "boiling_point": "5731",
                "electronegativity": "1.5",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "57.5",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "W": [
        AllotropeData(
            name="钨 单质",
            properties={
                "density": "19250",
                "melting_point": "3695",
                "boiling_point": "6203",
                "electronegativity": "2.36",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "173",
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Re": [
        AllotropeData(
            name="铼 单质",
            properties={
                "density": "21020",
                "melting_point": "3459",
                "boiling_point": "5869",
                "electronegativity": "1.9",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "48",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Os": [
        AllotropeData(
            name="锇 单质",
            properties={
                "density": "22590",
                "melting_point": "3306",
                "boiling_point": "5285",
                "electronegativity": "2.2",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "87.6",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Ir": [
        AllotropeData(
            name="铱 单质",
            properties={
                "density": "22560",
                "melting_point": "2719",
                "boiling_point": "4403",
                "electronegativity": "2.2",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "147",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Pt": [
        AllotropeData(
            name="铂 单质",
            properties={
                "density": "21450",
                "melting_point": "2041.4",
                "boiling_point": "4098",
                "electronegativity": "2.28",
                "vdw_radius": "1.75",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "71.6",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Au": [
        AllotropeData(
            name="金 单质",
            properties={
                "density": "19300",
                "melting_point": "1337.33",
                "boiling_point": "3243",
                "electronegativity": "2.54",
                "vdw_radius": "1.66",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "318",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Hg": [
        AllotropeData(
            name="汞 单质",
            properties={
                "density": "13534",
                "melting_point": "234.321",
                "boiling_point": "629.88",
                "electronegativity": "2",
                "vdw_radius": "1.55",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "8.3",
                "mohs_hardness": None,
                "crystal_structure": "RHL",
            },
        ),
    ],
    "Tl": [
        AllotropeData(
            name="铊 单质",
            properties={
                "density": "11850",
                "melting_point": "577",
                "boiling_point": "1746",
                "electronegativity": "1.62",
                "vdw_radius": "1.96",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "46.1",
                "mohs_hardness": None,
                "crystal_structure": "HEX",
            },
        ),
    ],
    "Pb": [
        AllotropeData(
            name="铅 单质",
            properties={
                "density": "11340",
                "melting_point": "600.61",
                "boiling_point": "2022",
                "electronegativity": "1.87",
                "vdw_radius": "2.02",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "35.3",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Bi": [
        AllotropeData(
            name="铋 单质",
            properties={
                "density": "9780",
                "melting_point": "544.7",
                "boiling_point": "1837",
                "electronegativity": "2.02",
                "vdw_radius": "2.07",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "7.9",
                "mohs_hardness": None,
                "crystal_structure": "RHL",
            },
        ),
    ],
    "Po": [
        AllotropeData(
            name="钋 单质",
            properties={
                "density": "9196",
                "melting_point": "527",
                "boiling_point": "1235",
                "electronegativity": "2",
                "vdw_radius": "1.97",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "SC",
            },
        ),
    ],
    "At": [
        AllotropeData(
            name="砹 单质",
            properties={
                "density": "6350",
                "melting_point": "575",
                "boiling_point": "610",
                "electronegativity": "2.2",
                "vdw_radius": "2.02",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Rn": [
        AllotropeData(
            name="氡 单质",
            properties={
                "density": "9.73",
                "melting_point": "202",
                "boiling_point": "211.5",
                "electronegativity": "2.2",
                "vdw_radius": "2.2",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "0.0036",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Fr": [
        AllotropeData(
            name="钫 单质",
            properties={
                "density": "1870",
                "melting_point": "300",
                "boiling_point": "950",
                "electronegativity": "0.79",
                "vdw_radius": "3.48",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "BCC",
            },
        ),
    ],
    "Ra": [
        AllotropeData(
            name="镭 单质",
            properties={
                "density": "5500",
                "melting_point": "1233",
                "boiling_point": "2010",
                "electronegativity": "0.9",
                "vdw_radius": "2.83",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "18.6",
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Ac": [
        AllotropeData(
            name="锕 单质",
            properties={
                "density": "10000",
                "melting_point": "1500",
                "boiling_point": "3500",
                "electronegativity": "1.1",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Ac": [
        AllotropeData(
            name="锕 单质",
            properties={
                "density": "10000",
                "melting_point": "1500",
                "boiling_point": "3500",
                "electronegativity": "1.1",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Th": [
        AllotropeData(
            name="钍 单质",
            properties={
                "density": "11724",
                "melting_point": "2023",
                "boiling_point": "5061",
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "54",
                "mohs_hardness": None,
                "crystal_structure": "FCC",
            },
        ),
    ],
    "Pa": [
        AllotropeData(
            name="镤 单质",
            properties={
                "density": "15370",
                "melting_point": "1841",
                "boiling_point": "4300",
                "electronegativity": "1.5",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "TET",
            },
        ),
    ],
    "U": [
        AllotropeData(
            name="铀 单质",
            properties={
                "density": "19100",
                "melting_point": "1405.3",
                "boiling_point": "4404",
                "electronegativity": "1.38",
                "vdw_radius": "1.86",
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "27.5",
                "mohs_hardness": None,
                "crystal_structure": "ORC",
            },
        ),
    ],
    "Np": [
        AllotropeData(
            name="镎 单质",
            properties={
                "density": "20450",
                "melting_point": "912",
                "boiling_point": "4447",
                "electronegativity": "1.36",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "6.3",
                "mohs_hardness": None,
                "crystal_structure": "ORC",
            },
        ),
    ],
    "Pu": [
        AllotropeData(
            name="钚 单质",
            properties={
                "density": "19816",
                "melting_point": "912.5",
                "boiling_point": "3505",
                "electronegativity": "1.28",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": "6.7",
                "mohs_hardness": None,
                "crystal_structure": "MCL",
            },
        ),
    ],
    "Am": [
        AllotropeData(
            name="镅 单质",
            properties={
                "density": "12000",
                "melting_point": "1449",
                "boiling_point": "2880",
                "electronegativity": "1.13",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Cm": [
        AllotropeData(
            name="锔 单质",
            properties={
                "density": "13510",
                "melting_point": "1613",
                "boiling_point": "3383",
                "electronegativity": "1.28",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Bk": [
        AllotropeData(
            name="锫 单质",
            properties={
                "density": "14780",
                "melting_point": "1259",
                "boiling_point": "2900",
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Cf": [
        AllotropeData(
            name="锎 单质",
            properties={
                "density": "15100",
                "melting_point": "1173",
                "boiling_point": "1743",
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Es": [
        AllotropeData(
            name="锿 单质",
            properties={
                "density": "8840",
                "melting_point": "1133",
                "boiling_point": "1269",
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Fm": [
        AllotropeData(
            name="镄 单质",
            properties={
                "density": None,
                "melting_point": "1800",
                "boiling_point": None,
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Md": [
        AllotropeData(
            name="钔 单质",
            properties={
                "density": None,
                "melting_point": "1100",
                "boiling_point": None,
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "No": [
        AllotropeData(
            name="锘 单质",
            properties={
                "density": None,
                "melting_point": "1100",
                "boiling_point": None,
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Lr": [
        AllotropeData(
            name="铹 单质",
            properties={
                "density": None,
                "melting_point": "1900",
                "boiling_point": None,
                "electronegativity": "1.3",
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Rf": [
        AllotropeData(
            name="𬬻 单质",
            properties={
                "density": "23200",
                "melting_point": "2400",
                "boiling_point": "5800",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Db": [
        AllotropeData(
            name="𬭊 单质",
            properties={
                "density": "29300",
                "melting_point": None,
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Sg": [
        AllotropeData(
            name="𬭳 单质",
            properties={
                "density": "35000",
                "melting_point": None,
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Bh": [
        AllotropeData(
            name="𬭛 单质",
            properties={
                "density": "37100",
                "melting_point": None,
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Hs": [
        AllotropeData(
            name="𬭶 单质",
            properties={
                "density": "40700",
                "melting_point": "126",
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Mt": [
        AllotropeData(
            name="鿏 单质",
            properties={
                "density": "37400",
                "melting_point": None,
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Ds": [
        AllotropeData(
            name="𫟼 单质",
            properties={
                "density": "34800",
                "melting_point": None,
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Rg": [
        AllotropeData(
            name="𬬭 单质",
            properties={
                "density": "28700",
                "melting_point": None,
                "boiling_point": None,
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Cn": [
        AllotropeData(
            name="鿔 单质",
            properties={
                "density": "14000",
                "melting_point": None,
                "boiling_point": "3570",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Nh": [
        AllotropeData(
            name="鿭 单质",
            properties={
                "density": "16000",
                "melting_point": "700",
                "boiling_point": "1430",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Fl": [
        AllotropeData(
            name="𫓧 单质",
            properties={
                "density": "14000",
                "melting_point": "340",
                "boiling_point": "420",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Mc": [
        AllotropeData(
            name="镆 单质",
            properties={
                "density": "13500",
                "melting_point": "670",
                "boiling_point": "1400",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Lv": [
        AllotropeData(
            name="𫟷 单质",
            properties={
                "density": "12900",
                "melting_point": "709",
                "boiling_point": "1085",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Ts": [
        AllotropeData(
            name="鿬 单质",
            properties={
                "density": "7170",
                "melting_point": "723",
                "boiling_point": "883",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],
    "Og": [
        AllotropeData(
            name="鿫 单质",
            properties={
                "density": "4950",
                "melting_point": None,
                "boiling_point": "350",
                "electronegativity": None,
                "vdw_radius": None,
                "speed_of_sound": None,
                "triple_point": None,
                "critical_point": None,
                "electrical_conductivity": None,
                "thermal_conductivity": None,
                "mohs_hardness": None,
                "crystal_structure": "",
            },
        ),
    ],}

DEFAULT_ALLOTROPES: Dict[str, List[AllotropeData]] = {
    element.symbol: [AllotropeData(name=f"{element.name_cn} 单质", properties={})]
    for element in ELEMENTS
}


def get_allotropes(symbol: str) -> List[AllotropeData]:
    return WIKIPEDIA_ALLOTROPES.get(symbol, DEFAULT_ALLOTROPES.get(symbol, []))
